#!/usr/bin/env bash
# run_fullperiod_visual_qc_pilot_h2o.sh
#
# Launcher for the Stage 1 full-period visual QC animation pilot on h2o.
# Run ONLY on h2o where the full-period forcing Parquets and v001 target
# package reside. For local (non-h2o) validation, use --dry-run.
#
# ── MODES ──────────────────────────────────────────────────────────────────
#
# DEFAULT — self-contained regeneration (no --vqc-csv):
#   Regenerates the visual QC case-selection CSV on h2o from the committed
#   scripts/generate_visual_qc_case_selection.py, then animates those cases.
#   Requires two h2o-local data inputs (both untracked by git):
#     1. Forcing audit tables (--audit-dir):
#          /data42/omrip/Flash-NH/tmp/stage1_forcing_fullperiod_postrun_audit_20260624T060504Z/
#          (contains fullperiod_gap_inventory.csv, fullperiod_basin_completeness.csv)
#     2. Basin metadata CSV (--meta-csv), relative to repo root:
#          reports/flashnh_usgs_site_metadata_v001/tables/wy2024_metrics_with_site_metadata.csv
#   If either is absent, the launcher fails with exact copy instructions.
#
# OVERRIDE — use an existing case-selection CSV (--vqc-csv PATH):
#   Skips CSV regeneration and uses the provided path directly.
#   Use this if you have already generated or rsync'd the CSV.
#
# ── USAGE ───────────────────────────────────────────────────────────────────
#
#   # Default: regenerate VQC CSV on h2o, then animate 6 pilot cases
#   bash scripts/run_fullperiod_visual_qc_pilot_h2o.sh
#
#   # Dry-run (no data read, no animations rendered; works locally)
#   bash scripts/run_fullperiod_visual_qc_pilot_h2o.sh --dry-run
#
#   # Override: skip CSV regeneration, use existing CSV
#   bash scripts/run_fullperiod_visual_qc_pilot_h2o.sh \
#       --vqc-csv /data42/omrip/Flash-NH/tmp/stage1_forcing_fullperiod_visual_qc_selection_20260625T081859Z/visual_qc_case_selection.csv
#
#   # Override audit-dir or meta-csv paths if timestamps differ
#   bash scripts/run_fullperiod_visual_qc_pilot_h2o.sh \
#       --audit-dir /data42/omrip/Flash-NH/tmp/stage1_forcing_fullperiod_postrun_audit_YYYYMMDDTHHMMSSZ
#
#   # Other options
#   bash scripts/run_fullperiod_visual_qc_pilot_h2o.sh --fps 6 --dpi 100 --overwrite
#
# ── OUTPUTS (not committed to git) ──────────────────────────────────────────
#
#   /data42/omrip/Flash-NH/tmp/stage1_forcing_fullperiod_visual_qc_pilot_<TIMESTAMP>/
#     vqc_case_selection/             (regenerated CSV + summary, if default mode)
#       visual_qc_case_selection.csv
#       summary.md
#     VQC-001/VQC-001_animation.gif
#     VQC-001/VQC-001_quicklook.png
#     ... (one subdir per case)
#     animation_manifest.csv
#     animation_summary.md
#     run.log

set -euo pipefail

# ---------------------------------------------------------------------------
# h2o-specific paths (do not change for local runs — use --dry-run instead)
# ---------------------------------------------------------------------------
H2O_FLASHNH_ROOT="/data42/omrip/Flash-NH"
ENV_PATH="${H2O_FLASHNH_ROOT}/envs/flashnh-stage1"
FORCING_ROOT="${H2O_FLASHNH_ROOT}/tmp/stage1_forcing_fullperiod"
TARGET_PKG_ROOT="${H2O_FLASHNH_ROOT}/tmp/stage1_target_package_v001"
TMP_ROOT="${H2O_FLASHNH_ROOT}/tmp"

# Audit table directory from the full-period forcing audit run (not in git).
# Expected to exist on h2o at this path (output of audit run 2026-06-24).
# Override with --audit-dir if the timestamp differs.
AUDIT_DIR="${H2O_FLASHNH_ROOT}/tmp/stage1_forcing_fullperiod_postrun_audit_20260624T060504Z"

# Required audit table filenames (must both be present in AUDIT_DIR)
AUDIT_FILE_GAP="fullperiod_gap_inventory.csv"
AUDIT_FILE_COMP="fullperiod_basin_completeness.csv"

# Repo root: script is in repo/scripts/, so repo root is one level up
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

# Basin metadata CSV path within the repo (untracked; generated by flashnh pipeline)
META_CSV="${REPO_ROOT}/reports/flashnh_usgs_site_metadata_v001/tables/wy2024_metrics_with_site_metadata.csv"

# Case-selection CSV: empty by default → will be regenerated on h2o.
# Set by --vqc-csv to skip regeneration.
VQC_CSV=""

# Pilot case IDs — exactly 6; matches PILOT_CASE_IDS in the animation script.
# Override with CASE_IDS env var.
CASE_IDS="${CASE_IDS:-VQC-001 VQC-004 VQC-007 VQC-009 VQC-012 VQC-020}"

# ---------------------------------------------------------------------------
# Default animation parameters (override on command line)
# ---------------------------------------------------------------------------
FPS=4
DPI=90
FORMAT="gif"
MAX_CASES=6
DRY_RUN_FLAG=""
CHECK_DATA_FLAG=""
OVERWRITE_FLAG=""

# ---------------------------------------------------------------------------
# Parse command-line args
# ---------------------------------------------------------------------------
while [[ $# -gt 0 ]]; do
    case "$1" in
        --dry-run)        DRY_RUN_FLAG="--dry-run" ;;
        --check-data)     CHECK_DATA_FLAG="--check-data" ;;
        --overwrite)      OVERWRITE_FLAG="--overwrite" ;;
        --fps)            FPS="$2";        shift ;;
        --dpi)            DPI="$2";        shift ;;
        --format)         FORMAT="$2";     shift ;;
        --max-cases)      MAX_CASES="$2";  shift ;;
        --case-ids)       CASE_IDS="$2";   shift ;;
        --vqc-csv)        VQC_CSV="$2";    shift ;;
        --audit-dir)      AUDIT_DIR="$2";  shift ;;
        --meta-csv)       META_CSV="$2";   shift ;;
        --help|-h)
            grep '^#' "${BASH_SOURCE[0]}" | sed 's/^# \?//'
            exit 0
            ;;
        *)
            echo "ERROR: Unknown option: $1" >&2; exit 1 ;;
    esac
    shift
done

# ---------------------------------------------------------------------------
# Timestamp for output directory (set once, before any logging)
# ---------------------------------------------------------------------------
TIMESTAMP="$(date -u +%Y%m%dT%H%M%SZ)"

# In dry-run mode outside h2o (TMP_ROOT absent), write to repo tmp/
if [[ -n "${DRY_RUN_FLAG}" && ! -d "${TMP_ROOT}" ]]; then
    OUT_DIR="${REPO_ROOT}/tmp/stage1_forcing_fullperiod_visual_qc_pilot_dryrun_${TIMESTAMP}"
else
    OUT_DIR="${TMP_ROOT}/stage1_forcing_fullperiod_visual_qc_pilot_${TIMESTAMP}"
fi

mkdir -p "${OUT_DIR}"
LOG="${OUT_DIR}/run.log"

# ---------------------------------------------------------------------------
# Logging helper
# ---------------------------------------------------------------------------
log() { echo "[$(date -u +%H:%M:%SZ)] $*" | tee -a "${LOG}"; }

# ---------------------------------------------------------------------------
# Banner
# ---------------------------------------------------------------------------
log "======================================================================"
log "Flash-NH Stage 1 — Full-period visual QC animation pilot"
log "======================================================================"
log "Mode:         ${DRY_RUN_FLAG:-RENDER}"
log "Timestamp:    ${TIMESTAMP}"
log "Output dir:   ${OUT_DIR}"
log "Repo root:    ${REPO_ROOT}"
log "Case IDs:     ${CASE_IDS}"

# ---------------------------------------------------------------------------
# Python environment — direct binary (conda prefix, no activate required)
# ---------------------------------------------------------------------------
PYTHON_BIN="${ENV_PATH}/bin/python"

if [[ ! -x "${PYTHON_BIN}" ]]; then
    log "ERROR: Python binary not found or not executable: ${PYTHON_BIN}"
    log "  Verify the conda prefix env exists: ls ${ENV_PATH}/bin/python"
    exit 1
fi

log "Python env:   ${ENV_PATH}"
log "Python bin:   ${PYTHON_BIN}"
log "Python ver:   $("${PYTHON_BIN}" --version 2>&1)"

# ---------------------------------------------------------------------------
# Verify committed scripts exist
# ---------------------------------------------------------------------------
VQC_SEL_SCRIPT="${REPO_ROOT}/scripts/generate_visual_qc_case_selection.py"
ANIM_SCRIPT="${REPO_ROOT}/scripts/generate_fullperiod_visual_qc_animations.py"

for SCRIPT in "${VQC_SEL_SCRIPT}" "${ANIM_SCRIPT}"; do
    if [[ ! -f "${SCRIPT}" ]]; then
        log "ERROR: required script not found: ${SCRIPT}"
        log "  Is the repo fully checked out at: ${REPO_ROOT}"
        exit 1
    fi
done
log "Scripts:      OK (generate_visual_qc_case_selection.py, generate_fullperiod_visual_qc_animations.py)"

# ---------------------------------------------------------------------------
# Resolve case-selection CSV
# Mode A: --vqc-csv provided → use it directly
# Mode B: default → regenerate from audit tables + metadata on h2o
# ---------------------------------------------------------------------------
if [[ -n "${VQC_CSV}" ]]; then
    # ---- Mode A: override ----
    log "VQC CSV:      [OVERRIDE] ${VQC_CSV}"
    if [[ ! -f "${VQC_CSV}" ]]; then
        log "ERROR: --vqc-csv path does not exist: ${VQC_CSV}"
        exit 1
    fi
    log "VQC CSV:      [OK] using provided CSV"

else
    # ---- Mode B: regenerate on h2o ----
    log "VQC CSV:      [REGENERATE] running generate_visual_qc_case_selection.py on h2o"

    # Check audit tables
    AUDIT_OK=true
    if [[ ! -d "${AUDIT_DIR}" ]]; then
        log "ERROR: audit directory not found: ${AUDIT_DIR}"
        AUDIT_OK=false
    else
        for AFILE in "${AUDIT_FILE_GAP}" "${AUDIT_FILE_COMP}"; do
            if [[ ! -f "${AUDIT_DIR}/${AFILE}" ]]; then
                log "ERROR: required audit file missing: ${AUDIT_DIR}/${AFILE}"
                AUDIT_OK=false
            fi
        done
    fi

    if [[ "${AUDIT_OK}" == "false" ]]; then
        log ""
        log "REQUIRED AUDIT TABLES NOT FOUND."
        log "The visual QC case-selection script needs the full-period forcing audit"
        log "output directory with at least these two files:"
        log "  ${AUDIT_DIR}/${AUDIT_FILE_GAP}"
        log "  ${AUDIT_DIR}/${AUDIT_FILE_COMP}"
        log ""
        log "To resolve — choose ONE of the following:"
        log "  Option 1 (transfer audit tables from local machine to h2o):"
        log "    rsync -av --progress LOCAL_REPO/tmp/stage1_forcing_fullperiod_postrun_audit_20260624T060504Z/ \\"
        log "        h2o:${AUDIT_DIR}/"
        log ""
        log "  Option 2 (use a pre-generated VQC CSV without re-running case selection):"
        log "    rsync -av LOCAL_REPO/tmp/stage1_forcing_fullperiod_visual_qc_selection_TIMESTAMP/ \\"
        log "        h2o:${TMP_ROOT}/stage1_forcing_fullperiod_visual_qc_selection_TIMESTAMP/"
        log "    bash scripts/run_fullperiod_visual_qc_pilot_h2o.sh \\"
        log "        --vqc-csv ${TMP_ROOT}/stage1_forcing_fullperiod_visual_qc_selection_TIMESTAMP/visual_qc_case_selection.csv"
        log ""
        log "  Option 3 (override audit-dir to a different path):"
        log "    bash scripts/run_fullperiod_visual_qc_pilot_h2o.sh \\"
        log "        --audit-dir /path/to/your/audit/dir"
        exit 1
    fi
    log "Audit dir:    ${AUDIT_DIR} [OK]"

    # Check metadata CSV
    if [[ ! -f "${META_CSV}" ]]; then
        log "ERROR: basin metadata CSV not found: ${META_CSV}"
        log ""
        log "REQUIRED METADATA CSV NOT FOUND."
        log "This file is not committed to git. To resolve — choose ONE of the following:"
        log "  Option 1 (transfer from local machine to h2o):"
        log "    rsync -av LOCAL_REPO/reports/flashnh_usgs_site_metadata_v001/tables/wy2024_metrics_with_site_metadata.csv \\"
        log "        h2o:${META_CSV}"
        log ""
        log "  Option 2 (use a pre-generated VQC CSV without re-running case selection):"
        log "    bash scripts/run_fullperiod_visual_qc_pilot_h2o.sh \\"
        log "        --vqc-csv /path/to/visual_qc_case_selection.csv"
        log ""
        log "  Option 3 (override meta-csv path):"
        log "    bash scripts/run_fullperiod_visual_qc_pilot_h2o.sh \\"
        log "        --meta-csv /path/to/wy2024_metrics_with_site_metadata.csv"
        exit 1
    fi
    log "Meta CSV:     ${META_CSV} [OK]"

    # Output directory for generated CSV (nested under pilot output dir)
    VQC_SEL_DIR="${OUT_DIR}/vqc_case_selection"
    log "VQC sel dir:  ${VQC_SEL_DIR}"

    # Generate the case-selection CSV
    log "Running:      generate_visual_qc_case_selection.py ..."
    SEL_CMD=(
        "${PYTHON_BIN}" "${VQC_SEL_SCRIPT}"
        --audit-dir   "${AUDIT_DIR}"
        --meta-csv    "${META_CSV}"
        --out-dir     "${VQC_SEL_DIR}"
    )
    log "CMD:          ${SEL_CMD[*]}"

    if [[ -n "${DRY_RUN_FLAG}" ]]; then
        log "[DRY-RUN] Skipping CSV generation (would run: ${SEL_CMD[*]})"
        # Create a placeholder path so the downstream dry-run can still validate
        VQC_CSV="${VQC_SEL_DIR}/visual_qc_case_selection.csv"
        log "[DRY-RUN] Expected CSV path: ${VQC_CSV}"
    else
        if "${SEL_CMD[@]}" 2>&1 | tee -a "${LOG}"; then
            VQC_CSV="${VQC_SEL_DIR}/visual_qc_case_selection.csv"
            if [[ ! -f "${VQC_CSV}" ]]; then
                log "ERROR: generate_visual_qc_case_selection.py ran but CSV not found: ${VQC_CSV}"
                exit 1
            fi
            log "VQC CSV:      [GENERATED] ${VQC_CSV}"
        else
            log "ERROR: generate_visual_qc_case_selection.py failed (exit ${?})"
            exit 1
        fi
    fi
fi

# ---------------------------------------------------------------------------
# Verify forcing root and target package root (skip in dry-run without --check-data)
# ---------------------------------------------------------------------------
if [[ -n "${CHECK_DATA_FLAG}" || -z "${DRY_RUN_FLAG}" ]]; then
    if [[ ! -d "${FORCING_ROOT}" ]]; then
        log "ERROR: forcing root not found: ${FORCING_ROOT}"
        [[ -z "${DRY_RUN_FLAG}" ]] && exit 1
        log "  (continuing in dry-run mode)"
    else
        log "Forcing root: ${FORCING_ROOT} [OK]"
    fi
    if [[ ! -d "${TARGET_PKG_ROOT}" ]]; then
        log "ERROR: target package root not found: ${TARGET_PKG_ROOT}"
        [[ -z "${DRY_RUN_FLAG}" ]] && exit 1
        log "  (continuing in dry-run mode)"
    else
        log "Target root:  ${TARGET_PKG_ROOT} [OK]"
    fi
fi

log "FPS=${FPS}  DPI=${DPI}  FORMAT=${FORMAT}  MAX_CASES=${MAX_CASES}"
log "======================================================================"

# ---------------------------------------------------------------------------
# Build animation command
# ---------------------------------------------------------------------------
# shellcheck disable=SC2206
IDS_ARRAY=(${CASE_IDS})

CMD=(
    "${PYTHON_BIN}" "${ANIM_SCRIPT}"
    --case-selection-csv "${VQC_CSV}"
    --case-ids "${IDS_ARRAY[@]}"
    --forcing-root       "${FORCING_ROOT}"
    --target-package-root "${TARGET_PKG_ROOT}"
    --out-dir            "${OUT_DIR}"
    --max-cases          "${MAX_CASES}"
    --fps                "${FPS}"
    --dpi                "${DPI}"
    --format             "${FORMAT}"
)

[[ -n "${DRY_RUN_FLAG}" ]]    && CMD+=("${DRY_RUN_FLAG}")
[[ -n "${CHECK_DATA_FLAG}" ]] && CMD+=("${CHECK_DATA_FLAG}")
[[ -n "${OVERWRITE_FLAG}" ]]  && CMD+=("${OVERWRITE_FLAG}")

log "Running: ${CMD[*]}"
log "======================================================================"

# ---------------------------------------------------------------------------
# Execute animation
# ---------------------------------------------------------------------------
T0="$(date +%s)"

if "${CMD[@]}" 2>&1 | tee -a "${LOG}"; then
    ANIM_EXIT=0
else
    ANIM_EXIT="${PIPESTATUS[0]:-1}"
fi

T1="$(date +%s)"
ELAPSED=$(( T1 - T0 ))

log "======================================================================"
log "Exit code:    ${ANIM_EXIT}"
log "Elapsed:      ${ELAPSED}s"
log "Output dir:   ${OUT_DIR}"
log "Log:          ${LOG}"

if [[ -z "${DRY_RUN_FLAG}" ]]; then
    log ""
    log "VQC CSV:      ${VQC_CSV}"
    log "Manifest:     ${OUT_DIR}/animation_manifest.csv"
    log "Summary:      ${OUT_DIR}/animation_summary.md"
    log ""
    log "To copy outputs from h2o to local (rsync example):"
    log "  rsync -av --progress h2o:${OUT_DIR}/ /path/to/local/qc_pilot/"
fi

log "======================================================================"
exit "${ANIM_EXIT}"