"""
select_second_pass_rule_review_set.py

Selects a targeted second-pass review set (~60 basins) from the corrected
rule-analysis output, writes sampling tables and summaries, then generates
hydrograph review cards for the selected basins.

Selection tiers
---------------
Tier 1  - HOLDOUT_REVIEW_PRELIM basins with >= 3 active C/D/E/G/H/J flags (up to 25)
Tier 2  - HOLDOUT_REVIEW_PRELIM, one diverse sub-sample per major rule family
           (rule_C ~8, rule_D ~8, rule_E ~8, rule_J ~8, rule_G ~5, rule_H ~5)
Tier 3a - Near-threshold TRAIN_SOFT_KEEP_PRELIM basins with >= 1 of C/D/E/J active (4)
Tier 3b - Clean TRAIN_CORE_PRELIM basins with no C/D/E/G/H/J active (4)

Exclusions (applied before all tiers)
--------------------------------------
- Basins already reviewed in first pass (73 basins)
- Basins with preliminary_training_status == EXCLUDE_TRAINING_PRELIM
- Basins with metadata_policy_bucket == HARD_EXCLUDE
- Basins with main_training_candidate != True

Outputs
-------
reports/flashnh_hydrograph_review_cards_v005_second_pass_rules/
  tables/second_pass_selected_basins.csv
  tables/second_pass_sampling_summary.csv
  summaries/second_pass_sampling_summary.md
  summaries/second_pass_sampling_summary.json
  plots/ <generated by build_hydrograph_review_cards.py>
  tables/review_card_manifest.csv
  tables/human_review_template.csv
"""

import json
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
REPO_ROOT = Path(__file__).resolve().parent.parent

RULE_MATRIX_CSV = (
    REPO_ROOT
    / "reports/flashnh_manual_review_rule_analysis_v001/tables/full_candidate_rule_matrix.csv"
)
FIRST_PASS_LABELS_CSV = (
    REPO_ROOT
    / "reports/flashnh_hydrograph_review_cards_v004_main_training_candidate"
    / "manual_review_labels.csv"
)
LOCKED_LABELS_CSV = (
    REPO_ROOT
    / "reports/flashnh_hydrograph_review_cards_v004_main_training_candidate"
    / "manual_review_labels_pass1_locked.csv"
)
METRICS_CSV = (
    REPO_ROOT
    / "reports/flashnh_usgs_site_metadata_v001/tables/wy2024_metrics_with_site_metadata.csv"
)
METRICS_DIR = REPO_ROOT / "reports/flashnh_usgs_site_metadata_v001"
OUT_DIR     = REPO_ROOT / "reports/flashnh_hydrograph_review_cards_v005_second_pass_rules"
BUILD_SCRIPT = REPO_ROOT / "scripts/build_hydrograph_review_cards.py"

# ---------------------------------------------------------------------------
# Selection parameters
# ---------------------------------------------------------------------------
SEED = 42

TIER1_MAX = 25
TIER2_TARGETS = {
    "rule_C": 8,
    "rule_D": 8,
    "rule_E": 8,
    "rule_J": 8,
    "rule_G": 5,
    "rule_H": 5,
}
TIER3_NEAR_THRESHOLD = 4
TIER3_CORE_CONTROL   = 4

# Rule columns used for the compound-risk count (C/D/E/G/H/J — excludes A/B/F/I)
CDEGHJCOLS = ["rule_C", "rule_D", "rule_E", "rule_G", "rule_H", "rule_J"]
ALL_RULE_COLS = ["rule_A", "rule_B", "rule_C", "rule_D", "rule_E",
                 "rule_F", "rule_G", "rule_H", "rule_I", "rule_J"]

# Primary sort variable per rule (most extreme first)
RULE_SORT_VAR = {
    "rule_C": "WATERNLCD06",
    "rule_D": "CANALS_PCT",
    "rule_E": "HYDRO_DISTURB_INDX",
    "rule_J": "compound_risk_count",
    "rule_G": "zero_flow_fraction",
    "rule_H": "max_abs_hourly_jump_over_Q50",
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def _make_area_bin(sqkm):
    try:
        v = float(sqkm)
        if v < 10:  return "1-10 km2"
        if v < 100: return "10-100 km2"
        return "100-1000 km2"
    except Exception:
        return "unknown"


def _make_rbi_bin(rbi):
    try:
        r = float(rbi)
        if r < 0.01: return "RBI<0.01"
        if r < 0.03: return "RBI 0.01-0.03"
        if r < 0.10: return "RBI 0.03-0.10"
        if r < 0.30: return "RBI 0.10-0.30"
        return "RBI>=0.30"
    except Exception:
        return "unknown"


def _make_bfi_bin(bfi):
    try:
        b = float(bfi)
        if b <= 20: return "<=20"
        if b <= 30: return "20-30"
        if b <= 40: return "30-40"
        if b <= 50: return "40-50"
        return ">50"
    except Exception:
        return "unknown"


def _active_rules_str(row):
    active = [r for r in ALL_RULE_COLS if bool(row.get(r, False))]
    return "|".join(active) if active else ""


def _diverse_select(pool: pd.DataFrame, n: int, sort_desc_col: str = None) -> pd.DataFrame:
    """Select up to n rows from pool, maximising HUC02 diversity.

    Strategy: round-robin by HUC02, within each HUC take the highest-scoring
    row (by sort_desc_col descending). Deterministic, no random sampling.
    """
    if len(pool) <= n:
        return pool.copy()

    if sort_desc_col and sort_desc_col in pool.columns:
        pool = pool.sort_values(sort_desc_col, ascending=False)
    else:
        pool = pool.copy()

    # Build ordered list of HUCs sorted by count desc (most-represented first)
    hucs = pool["HUC02"].fillna("unknown")
    huc_order = hucs.value_counts().index.tolist()

    selected = []
    remaining = pool.copy()

    while len(selected) < n and not remaining.empty:
        made_progress = False
        for huc in huc_order:
            if len(selected) >= n:
                break
            sub = remaining[remaining["HUC02"].fillna("unknown") == huc]
            if len(sub) > 0:
                chosen = sub.iloc[0]
                selected.append(chosen)
                remaining = remaining[remaining["STAID"] != chosen["STAID"]]
                made_progress = True
        if not made_progress:
            break

    if len(selected) < n and not remaining.empty:
        # Top up from remaining (already sorted by sort_desc_col)
        for _, r in remaining.head(n - len(selected)).iterrows():
            selected.append(r)

    result = pd.DataFrame(selected).drop_duplicates("STAID")
    return result.head(n)


def _stratified_select(pool: pd.DataFrame, n: int, strat_cols: list) -> pd.DataFrame:
    """Select n rows from pool by evenly spacing across sorted strat_cols."""
    if len(pool) <= n:
        return pool.copy()
    df_sorted = pool.sort_values(strat_cols).reset_index(drop=True)
    indices = list(dict.fromkeys(
        np.round(np.linspace(0, len(df_sorted) - 1, n)).astype(int).tolist()
    ))[:n]
    return df_sorted.iloc[indices].copy()


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main() -> int:
    print("=" * 62)
    print("Flash-NH Second-Pass Rule Review Set Selector")
    print("=" * 62)

    # ── Create locked labels copy if missing ──────────────────────────────
    if FIRST_PASS_LABELS_CSV.exists() and not LOCKED_LABELS_CSV.exists():
        shutil.copy2(FIRST_PASS_LABELS_CSV, LOCKED_LABELS_CSV)
        print(f"Created locked labels copy: {LOCKED_LABELS_CSV.name}")
    elif LOCKED_LABELS_CSV.exists():
        print(f"Locked labels copy already exists: {LOCKED_LABELS_CSV.name}")
    else:
        print(f"WARNING: First-pass labels not found at {FIRST_PASS_LABELS_CSV}")

    # ── Load inputs ────────────────────────────────────────────────────────
    print("\nLoading inputs...")

    rm = pd.read_csv(RULE_MATRIX_CSV, dtype={"STAID": str})
    print(f"  Rule matrix: {len(rm)} rows")
    assert len(rm) == 3034, f"Expected 3034 rows in rule matrix, got {len(rm)}"

    labels = pd.read_csv(FIRST_PASS_LABELS_CSV, dtype={"STAID": str})
    print(f"  First-pass labels: {len(labels)} rows")
    assert len(labels) == 73, f"Expected 73 first-pass labels, got {len(labels)}"

    # ── Enrich rule matrix ─────────────────────────────────────────────────
    present_cdeghjcols = [c for c in CDEGHJCOLS if c in rm.columns]
    present_all_rules  = [c for c in ALL_RULE_COLS if c in rm.columns]

    rm["cdeghjcount"]    = rm[present_cdeghjcols].astype(int).sum(axis=1)
    rm["active_rules"]   = rm.apply(_active_rules_str, axis=1)
    rm["active_rule_count"] = rm[present_all_rules].astype(int).sum(axis=1)
    rm["area_bin"]       = rm["DRAIN_SQKM"].apply(_make_area_bin)
    rm["rbi_bin"]        = rm["RBI"].apply(_make_rbi_bin)
    rm["bfi_bin"]        = rm["BFI_AVE"].apply(_make_bfi_bin)

    # ── Build eligibility pool ─────────────────────────────────────────────
    reviewed_staids = set(labels["STAID"].astype(str))

    pool = rm[
        (~rm["STAID"].isin(reviewed_staids)) &
        (rm["metadata_policy_bucket"] != "HARD_EXCLUDE") &
        (rm["main_training_candidate"].astype(str).str.upper().isin({"TRUE", "1", "YES"})) &
        (rm["preliminary_training_status"] != "EXCLUDE_TRAINING_PRELIM")
    ].copy()

    holdout = pool[pool["preliminary_training_status"] == "HOLDOUT_REVIEW_PRELIM"].copy()
    soft    = pool[pool["preliminary_training_status"] == "TRAIN_SOFT_KEEP_PRELIM"].copy()
    core    = pool[pool["preliminary_training_status"] == "TRAIN_CORE_PRELIM"].copy()

    print(f"\nEligible pool: {len(pool)} basins")
    print(f"  HOLDOUT_REVIEW_PRELIM:  {len(holdout)}")
    print(f"  TRAIN_SOFT_KEEP_PRELIM: {len(soft)}")
    print(f"  TRAIN_CORE_PRELIM:      {len(core)}")

    selected_staids: set = set()
    tier_frames: list = []

    # ── Tier 1: compound risk >= 3 ─────────────────────────────────────────
    tier1_pool = holdout[holdout["cdeghjcount"] >= 3].copy()
    t1 = _diverse_select(tier1_pool, TIER1_MAX, sort_desc_col="cdeghjcount")
    t1 = t1.copy()
    t1["sampling_tier"]          = "tier1_compound_risk"
    t1["dominant_review_reason"] = "compound_risk_ge3"
    t1["reference_anchor"]       = False
    t1["final_recommended_action"] = ""
    selected_staids.update(t1["STAID"].tolist())
    tier_frames.append(t1)
    print(f"\nTier 1 (compound risk >= 3): {len(t1)} basins selected from {len(tier1_pool)} candidates")

    # ── Tier 2: per-rule validation ────────────────────────────────────────
    print("\nTier 2 per-rule sampling:")
    for rule, target_n in TIER2_TARGETS.items():
        if rule not in holdout.columns:
            print(f"  {rule}: column missing, skipped")
            continue
        rule_pool = holdout[
            holdout[rule].astype(bool) &
            (~holdout["STAID"].isin(selected_staids))
        ].copy()
        if len(rule_pool) == 0:
            print(f"  {rule}: 0 candidates available")
            continue

        sort_col = RULE_SORT_VAR.get(rule)
        t2 = _diverse_select(rule_pool, target_n, sort_desc_col=sort_col)
        t2 = t2.copy()
        t2["sampling_tier"]          = f"tier2_{rule}"
        t2["dominant_review_reason"] = rule
        t2["reference_anchor"]       = False
        t2["final_recommended_action"] = ""
        selected_staids.update(t2["STAID"].tolist())
        tier_frames.append(t2)
        print(f"  {rule}: {len(t2)} basins (from {len(rule_pool)} candidates)")

    # ── Tier 3a: near-threshold SOFT_KEEP ─────────────────────────────────
    soft_near = soft[
        soft[["rule_C", "rule_D", "rule_E", "rule_J"]].astype(bool).any(axis=1) &
        (~soft["STAID"].isin(selected_staids))
    ].copy()
    t3a = _stratified_select(soft_near, TIER3_NEAR_THRESHOLD, ["HUC02", "area_bin"])
    t3a = t3a.copy()
    t3a["sampling_tier"]          = "tier3_near_threshold"
    t3a["dominant_review_reason"] = "near_threshold_control"
    t3a["reference_anchor"]       = False
    t3a["final_recommended_action"] = ""
    selected_staids.update(t3a["STAID"].tolist())
    tier_frames.append(t3a)
    print(f"\nTier 3a (near-threshold SOFT_KEEP): {len(t3a)} basins from {len(soft_near)} candidates")

    # ── Tier 3b: clean CORE controls ──────────────────────────────────────
    core_clean = core[
        (~core[present_cdeghjcols].astype(bool).any(axis=1)) &
        (~core["STAID"].isin(selected_staids))
    ].copy()
    t3b = _stratified_select(core_clean, TIER3_CORE_CONTROL, ["HUC02", "area_bin", "bfi_bin"])
    t3b = t3b.copy()
    t3b["sampling_tier"]          = "tier3_core_control"
    t3b["dominant_review_reason"] = "clean_control"
    t3b["reference_anchor"]       = False
    t3b["final_recommended_action"] = ""
    selected_staids.update(t3b["STAID"].tolist())
    tier_frames.append(t3b)
    print(f"Tier 3b (clean CORE controls): {len(t3b)} basins from {len(core_clean)} candidates")

    # ── Combine ────────────────────────────────────────────────────────────
    selected = pd.concat(tier_frames, ignore_index=True).drop_duplicates("STAID").reset_index(drop=True)
    print(f"\nTotal selected: {len(selected)} basins")

    # ── Validation ─────────────────────────────────────────────────────────
    print("\nRunning validation checks...")

    # Check 1: rule matrix rows
    assert len(rm) == 3034, "Check 1 FAIL: rule matrix != 3034 rows"
    print("  Check 1 (rule matrix rows = 3034): PASS")

    # Check 2: first-pass labels rows
    assert len(labels) == 73, "Check 2 FAIL: first-pass labels != 73 rows"
    print("  Check 2 (first-pass labels rows = 73): PASS")

    # Check 3: selected count
    print(f"  Check 3 (selected count): {len(selected)} basins")

    # Check 4: no first-pass reviewed unless reference_anchor
    v4 = selected[
        selected["STAID"].isin(reviewed_staids) &
        (~selected["reference_anchor"].astype(bool))
    ]
    assert len(v4) == 0, f"Check 4 FAIL: {len(v4)} first-pass reviewed basins without reference_anchor"
    print(f"  Check 4 (no first-pass reviewed without anchor): PASS (0 violations)")

    # Check 5: no HARD_EXCLUDE
    v5 = selected[selected["metadata_policy_bucket"] == "HARD_EXCLUDE"]
    assert len(v5) == 0, f"Check 5 FAIL: {len(v5)} HARD_EXCLUDE basins in selection"
    print(f"  Check 5 (no HARD_EXCLUDE): PASS")

    # Check 6: all non-reference have main_training_candidate == True
    non_ref = selected[~selected["reference_anchor"].astype(bool)]
    v6 = non_ref[~non_ref["main_training_candidate"].astype(str).str.upper().isin({"TRUE", "1", "YES"})]
    assert len(v6) == 0, f"Check 6 FAIL: {len(v6)} without main_training_candidate"
    print(f"  Check 6 (all main_training_candidate == True): PASS")

    # Check 7: no EXCLUDE_TRAINING_PRELIM
    v7 = selected[selected["preliminary_training_status"] == "EXCLUDE_TRAINING_PRELIM"]
    assert len(v7) == 0, f"Check 7 FAIL: {len(v7)} EXCLUDE_TRAINING_PRELIM in selection"
    print(f"  Check 7 (no EXCLUDE_TRAINING_PRELIM): PASS")

    reference_anchors_n = int(selected["reference_anchor"].astype(bool).sum())
    print(f"  Reference anchors included: {reference_anchors_n}")

    # ── Write tables ───────────────────────────────────────────────────────
    print("\nWriting outputs...")
    tables_dir = OUT_DIR / "tables"
    summ_dir   = OUT_DIR / "summaries"
    tables_dir.mkdir(parents=True, exist_ok=True)
    summ_dir.mkdir(parents=True, exist_ok=True)

    selected_csv = tables_dir / "second_pass_selected_basins.csv"
    selected.to_csv(selected_csv, index=False)
    print(f"  Wrote: {selected_csv.name}")

    # Per-tier sampling summary table
    sampling_rows = []
    for tier, grp in selected.groupby("sampling_tier", sort=False):
        sampling_rows.append({
            "sampling_tier":        tier,
            "n_basins":             len(grp),
            "dominant_reason":      ", ".join(sorted(grp["dominant_review_reason"].unique())),
            "huc02_n_distinct":     int(grp["HUC02"].nunique()),
            "area_bin_dist":        str(grp["area_bin"].value_counts().to_dict()),
            "candidate_class_dist": str(grp["candidate_class"].value_counts().to_dict()),
            "prelim_status_dist":   str(grp["preliminary_training_status"].value_counts().to_dict()),
        })
    pd.DataFrame(sampling_rows).to_csv(tables_dir / "second_pass_sampling_summary.csv", index=False)
    print(f"  Wrote: second_pass_sampling_summary.csv")

    # Summaries (JSON + Markdown)
    generated_at = datetime.now(timezone.utc).isoformat()
    summary_json = {
        "generated_at":    generated_at,
        "seed":            SEED,
        "total_selected":  int(len(selected)),
        "by_sampling_tier": {k: int(v) for k, v in selected["sampling_tier"].value_counts().items()},
        "by_dominant_review_reason": {k: int(v) for k, v in selected["dominant_review_reason"].value_counts().items()},
        "by_candidate_class": {k: int(v) for k, v in selected["candidate_class"].value_counts().items()},
        "by_preliminary_training_status": {k: int(v) for k, v in selected["preliminary_training_status"].value_counts().items()},
        "by_active_rule_count": {int(k): int(v) for k, v in selected["active_rule_count"].value_counts().sort_index().items()},
        "by_huc02": {str(k): int(v) for k, v in selected["HUC02"].value_counts().items()},
        "by_area_bin": {k: int(v) for k, v in selected["area_bin"].value_counts().items()},
        "by_bfi_bin":  {k: int(v) for k, v in selected["bfi_bin"].value_counts().items()},
        "by_rbi_bin":  {k: int(v) for k, v in selected["rbi_bin"].value_counts().items()},
        "reference_anchors_n": reference_anchors_n,
        "validation_checks": {
            "rule_matrix_rows": 3034,
            "first_pass_labels_rows": 73,
            "first_pass_in_selection_no_anchor": int(len(v4)),
            "hard_exclude_in_selection": int(len(v5)),
            "exclude_prelim_in_selection": int(len(v7)),
        },
    }
    with open(summ_dir / "second_pass_sampling_summary.json", "w") as f:
        json.dump(summary_json, f, indent=2, default=str)
    print(f"  Wrote: second_pass_sampling_summary.json")

    md_lines = [
        "# Flash-NH Second-Pass Rule Review — Sampling Summary",
        f"\nGenerated: {generated_at}",
        f"\n**Total selected**: {len(selected)} basins",
        f"**Reference anchors**: {reference_anchors_n}",
        "\n## By sampling tier",
    ]
    for k, v in summary_json["by_sampling_tier"].items():
        md_lines.append(f"- {k}: {v}")
    md_lines.append("\n## By dominant review reason")
    for k, v in summary_json["by_dominant_review_reason"].items():
        md_lines.append(f"- {k}: {v}")
    md_lines.append("\n## By candidate class")
    for k, v in summary_json["by_candidate_class"].items():
        md_lines.append(f"- {k}: {v}")
    md_lines.append("\n## By preliminary training status")
    for k, v in summary_json["by_preliminary_training_status"].items():
        md_lines.append(f"- {k}: {v}")
    md_lines.append("\n## By active rule count")
    for k, v in sorted(summary_json["by_active_rule_count"].items()):
        md_lines.append(f"- {k} active rules: {v}")
    md_lines.append("\n## By HUC02")
    for k, v in sorted(summary_json["by_huc02"].items()):
        md_lines.append(f"- HUC {k}: {v}")
    md_lines.append("\n## By area bin")
    for k, v in summary_json["by_area_bin"].items():
        md_lines.append(f"- {k}: {v}")
    md_lines.append("\n## By BFI bin")
    for k, v in summary_json["by_bfi_bin"].items():
        md_lines.append(f"- {k}: {v}")
    md_lines.append("\n## Validation checks")
    md_lines.append(f"- Rule matrix rows: {summary_json['validation_checks']['rule_matrix_rows']} (expected 3034)")
    md_lines.append(f"- First-pass labels rows: {summary_json['validation_checks']['first_pass_labels_rows']} (expected 73)")
    md_lines.append(f"- First-pass basins in selection without anchor (must be 0): {summary_json['validation_checks']['first_pass_in_selection_no_anchor']}")
    md_lines.append(f"- HARD_EXCLUDE in selection (must be 0): {summary_json['validation_checks']['hard_exclude_in_selection']}")
    md_lines.append(f"- EXCLUDE_TRAINING_PRELIM in selection (must be 0): {summary_json['validation_checks']['exclude_prelim_in_selection']}")
    (summ_dir / "second_pass_sampling_summary.md").write_text("\n".join(md_lines), encoding="utf-8")
    print(f"  Wrote: second_pass_sampling_summary.md")

    # ── Generate review cards ──────────────────────────────────────────────
    sys.stdout.flush()
    print("\n" + "=" * 62)
    print("Generating hydrograph review cards...")
    print("=" * 62)
    sys.stdout.flush()
    cmd = [
        sys.executable, "-u", str(BUILD_SCRIPT),
        "--output-dir",          str(OUT_DIR),
        "--metrics-dir",         str(METRICS_DIR),
        "--metrics-file",        "tables/wy2024_metrics_with_site_metadata.csv",
        "--selected-staids-csv", str(selected_csv),
        "--no-show",
    ]
    print("Command:", " ".join(str(c) for c in cmd))
    result = subprocess.run(cmd)
    if result.returncode != 0:
        print(f"Card builder exited with non-zero code: {result.returncode}")
        return result.returncode

    print("\n" + "=" * 62)
    print("Done.")
    print(f"  Output dir: {OUT_DIR}")
    print(f"  Selected:   {len(selected)} basins")
    return 0


if __name__ == "__main__":
    sys.exit(main())
