# Workflow to run the pytest test suite.

name: pytest CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    name: PyTest CI (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: neuralhydrology
          environment-file: environments/environment_cpu.yml
          python-version: "3.10"
          auto-activate-base: false
      - run: |
          pytest --cov=neuralhydrology